apiVersion : apps/v1
kind: Deployment
metadata:
  name: komodor-demo 
  annotations:
    app.komodor.com/app: https://github.com/n3wt0n/Deploy-to-AKS
    app.komodor.com/app.ref: #{SOURCEVERSION}#
    app.komodor.com/deploy.link.davide: "https://ciao.gino.it"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komodor-demo
  template:
    metadata:
      labels:
        app: komodor-demo 
    spec:
      containers:
        - name: komodor-demo 
          image: nginx
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: 500m
            limits:
              memory: "512Mi"
              cpu: 600m
